### ISSUE TITLE
xformer no longer works with torch2.0.1

### ISSUE THREAD

**Issue by SimonSun0810** [kylesargent/zeronvs#25]
> 
> (zero) (base) xsun2609@gpu1-119-1:~/pycharmfile/ZeroNVS-main$ source launch_eval_dtu.sh
> eval_outputs/DTU/8
> 8
> 1.2
> WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
>     PyTorch 2.3.1+cu118 with CUDA 1108 (you have 2.0.1+cu118)
>     Python  3.8.19 (you have 3.8.19)
>   Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
>   Memory-efficient attention, SwiGLU, sparse and more won't be available.
>   Set XFORMERS_MORE_DETAILS=1 for more details
> Traceback (most recent call last):
>   File "/home/xsun2609/anaconda3/envs/zero/lib/python3.8/site-packages/xformers/checkpoint.py", line 53, in <module>
>     from torch.utils.checkpoint import SAC_IGNORED_OPS as _ignored_ops  # type: ignore
> ImportError: cannot import name 'SAC_IGNORED_OPS' from 'torch.utils.checkpoint' (/home/xsun2609/anaconda3/envs/zero/lib/python3.8/site-packages/torch/utils/checkpoint.py)
> 

This was the output when setting torch==2.0.1, cuda==11.8. I had two chiose, one is changing the version of xformer to match torch==2.0.1, cuda==11.8 but no longer use, another is change the version of torch to 2.3.1 but it will conflict with others, as shown below:

> (zero) (base) xsun2609@gpu1-119-1:~/pycharmfile/ZeroNVS-main$ source launch_eval_dtu.sh
> eval_outputs/DTU/8
> 8
> 1.2
> Traceback (most recent call last):
>   File "launch.py", line 254, in <module>
>     main(args, extras)
>   File "launch.py", line 83, in main
>     import threestudio
>   File "/home/xsun2609/pycharmfile/ZeroNVS-main/threestudio/__init__.py", line 36, in <module>
>     from . import data, models, systems
>   File "/home/xsun2609/pycharmfile/ZeroNVS-main/threestudio/data/__init__.py", line 1, in <module>
>     from . import co3d, image, multiview, uncond
>   File "/home/xsun2609/pycharmfile/ZeroNVS-main/threestudio/data/co3d.py", line 17, in <module>
>     from threestudio.data.uncond import (
>   File "/home/xsun2609/pycharmfile/ZeroNVS-main/threestudio/data/uncond.py", line 13, in <module>
>     from threestudio.utils.base import Updateable
>   File "/home/xsun2609/pycharmfile/ZeroNVS-main/threestudio/utils/__init__.py", line 1, in <module>
>     from . import base
>   File "/home/xsun2609/pycharmfile/ZeroNVS-main/threestudio/utils/base.py", line 7, in <module>
>     from threestudio.utils.misc import get_device, load_module_weights
>   File "/home/xsun2609/pycharmfile/ZeroNVS-main/threestudio/utils/misc.py", line 5, in <module>
>     import tinycudann as tcnn
>   File "/home/xsun2609/anaconda3/envs/zero/lib/python3.8/site-packages/tinycudann/__init__.py", line 9, in <module>
>     from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
>   File "/home/xsun2609/anaconda3/envs/zero/lib/python3.8/site-packages/tinycudann/modules.py", line 55, in <module>
>     _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
>   File "/home/xsun2609/anaconda3/envs/zero/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: /home/xsun2609/anaconda3/envs/zero/lib/python3.8/site-packages/tinycudann_bindings/_89_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

This was the output when setting torch==2.3.1, cuda==11.8.

**Comment by Whiteneko24** [comment]
Has the issue been resolved?
